-- Table 1:



CREATE TABLE shooting (
    INCIDENT_KEY INT PRIMARY KEY,
    BORO VARCHAR(50),
    LOC_OF_OCCUR_DESC VARCHAR(100),
    PRECINCT INT,
    JURISDICTION_CODE FLOAT,
    LOC_CLASSFCTN_DESC VARCHAR(250),
    LOCATION_DESC VARCHAR(250),
    STATISTICAL_MURDER_FLAG BOOLEAN,
    PERP_AGE_GROUP VARCHAR(250),
    PERP_SEX CHAR(10),
    PERP_RACE VARCHAR(250),
    VIC_AGE_GROUP VARCHAR(250),
    VIC_SEX CHAR(10),
    VIC_RACE VARCHAR(250)
);



-- Table 2:
CREATE TABLE dates (
    INCIDENT_KEY INT PRIMARY KEY,
    OCCUR_DATE DATE,
    OCCUR_TIME TIME,
    FOREIGN KEY (INCIDENT_KEY) REFERENCES shooting (INCIDENT_KEY)
);

-- Table 3:
CREATE TABLE geolocation (
    INCIDENT_KEY INT PRIMARY KEY,
    X_COORD_CD VARCHAR(50),
    Y_COORD_CD VARCHAR(50),
    Latitude FLOAT,
    Longitude FLOAT
    FOREIGN KEY (INCIDENT_KEY) REFERENCES shooting (INCIDENT_KEY)
);



