-- Table 1:
CREATE TABLE shooting (
    INCIDENT_KEY INT PRIMARY KEY,
    BORO VARCHAR(50),
    LOC_OF_OCCUR_DESC VARCHAR(100),
    PRECINCT INT,
    JURISDICTION_CODE INT,
    LOC_CLASSFCTN_DESC VARCHAR(100),
    LOCATION_DESC VARCHAR(100),
    STATISTICAL_MURDER_FLAG BOOLEAN,
    PERP_AGE_GROUP VARCHAR(20),
    PERP_SEX CHAR(1),
    PERP_RACE VARCHAR(20),
    VIC_AGE_GROUP VARCHAR(10),
    VIC_SEX CHAR(1),
    VIC_RACE VARCHAR(20)
);

-- Table 2:
CREATE TABLE dates (
    INCIDENT_KEY INT PRIMARY KEY,
    OCCUR_DATE DATE,
    OCCUR_TIME TIME,
    FOREIGN KEY (INCIDENT_KEY) REFERENCES shooting (INCIDENT_KEY)
);

-- Table 3:
CREATE TABLE location (
    INCIDENT_KEY INT PRIMARY KEY,
    X_COORD_CD FLOAT,
    Y_COORD_CD FLOAT,
    Latitude FLOAT,
    Longitude FLOAT,
    Lon_Lat VARCHAR(100),
    FOREIGN KEY (INCIDENT_KEY) REFERENCES shooting (INCIDENT_KEY)
);